# Generated by Django 2.2.20 on 2021-04-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, db_column='account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturer',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, max_length=80, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('occupy', models.CharField(blank=True, max_length=80, null=True)),
                ('graduated_university', models.CharField(blank=True, max_length=80, null=True)),
                ('accumulated_online_time', models.DateTimeField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=80, null=True)),
                ('account', models.ForeignKey(blank=True, db_column='account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, db_column='course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='LecturerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('lecturer', models.ForeignKey(blank=True, db_column='lecturer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Lecturer')),
                ('student', models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student')),
            ],
            options={
                'db_table': 'lecturer_rating',
            },
        ),
    ]
