# Generated by Django 2.2.3 on 2021-04-17 07:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='achievements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='bio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='designation',
            field=models.CharField(default='Associate Professor', max_length=100),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='profile_pic',
            field=models.ImageField(default='nopic.jpg', upload_to=users.models.Lecturer.profile_pic_path),
        ),
    ]
