# Generated by Django 2.2.20 on 2021-04-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrating',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student'),
        ),
        migrations.AddField(
            model_name='subjectrating',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Category'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.DO_NOTHING, to='course.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Faculty'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Category'),
        ),
    ]
