# Generated by Django 2.2.3 on 2021-04-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0002_auto_20210415_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='lecturer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Lecturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='requirements',
            field=models.TextField(default='no pre requisite'),
            preserve_default=False,
        ),
    ]
