# Generated by Django 2.2.3 on 2021-04-17 09:05

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210417_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pic',
            field=models.ImageField(default='nopic.jpg', upload_to=course.models.Subject.subject_pic_path),
        ),
    ]
